skinparam dpi 250
skinparam handwritten true
allow_mixing

skinparam defaultFontName  Open Sans
skinparam packagestyle rect

skinparam package {
	ArrowColor black

	borderColor #566573
	backgroundColor #FFFFFF
	fontSize 12
	fontColor #566573
}

skinparam node {
	ArrowColor black

	borderColor #566573
	backgroundColor #FFFFFF
	fontSize 12
	fontColor #566573
}

skinparam database {
	borderColor #333333
	backgroundColor #EEEEEEEE
}

skinparam agent {
	borderColor #566573
	backgroundColor #FFFFFF
    borderColor<<frontend>> #D2B4DE
    borderColor<<application>> #4695EB
}

skinparam stereotype {
    fontColor<<application>> #FFFFFF
}

skinparam arrow {
  color #4695EB
  fontColor #777777
  thickness 2
  fontSize 11
}

skinparam class {
  backgroundColor #FFFFFF
}
