@startuml
!include style.puml

left to right direction

package "Super Hero UI" as ui {
    agent "Quarkus" <<frontend>> as uiQuarkus
}

package "Hero" as hero {
    agent "Quarkus (reactive)" <<application>> as heroQuarkus
    database "Postgresql" as heroPostgresql
    heroQuarkus .up> heroPostgresql
}

package "Villain" as villain {
    agent "Quarkus (imperative)" <<application>> as villainQuarkus
    database "Postgresql" as villainPostgresql
    villainQuarkus .up> villainPostgresql
}

package "Fight" as fight {
    agent "Quarkus" <<application>> as fightQuarkus
    database "Postgresql" as fightPostgresql
    fightQuarkus .up> fightPostgresql
}

package "stats" {
    package "Statistics" as stat {
        agent "HTML+JQuery" <<frontend>> as statUI
        agent "Quarkus (imperative)" <<application>> as statQuarkus
        statUI .up> statQuarkus
    }

    package "Statistics UI" as statUi {
            agent "Browser" <<frontend>> as uiStats
    }
}

node "Kafka + Zookeeper" as kafka {
}

uiQuarkus --> fightQuarkus : HTTP
fightQuarkus --> heroQuarkus : HTTP
fightQuarkus --> villainQuarkus : HTTP

fightQuarkus ..> kafka : Message
stat <.. kafka : Message
statQuarkus ..> uiStats : Web Sockets

@enduml
